// Mock data generator for fallback when database has RLS issues
export const generateMockData = {
  clients: () => [
    {
      id: 'mock-client-1',
      agency_id: 'a1b2c3d4-e5f6-7890-1234-567890abcdef',
      email: 'john@techstartup.com',
      full_name: 'John Smith',
      company_name: 'Tech Startup Inc',
      phone: '+1 (555) 123-4567',
      status: 'active',
      onboarding_template_id: null,
      assigned_user_id: null,
      created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'mock-client-2',
      agency_id: 'a1b2c3d4-e5f6-7890-1234-567890abcdef',
      email: 'sarah@designco.com',
      full_name: 'Sarah Johnson',
      company_name: 'Design Co',
      phone: '+1 (555) 987-6543',
      status: 'active',
      onboarding_template_id: null,
      assigned_user_id: null,
      created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'mock-client-3',
      agency_id: 'a1b2c3d4-e5f6-7890-1234-567890abcdef',
      email: 'mike@consulting.com',
      full_name: 'Mike Wilson',
      company_name: 'Wilson Consulting',
      phone: '+1 (555) 456-7890',
      status: 'inactive',
      onboarding_template_id: null,
      assigned_user_id: null,
      created_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],

  tasks: () => [
    {
      id: 'mock-task-1',
      client_id: 'mock-client-1',
      template_task_id: null,
      title: 'Complete Business Registration',
      description: 'Register your business with the state and obtain necessary licenses',
      task_type: 'account_creation',
      status: 'pending',
      order_index: 1,
      required: true,
      due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      estimated_duration: 120,
      instructions: 'Please visit the state website and complete the business registration form',
      metadata: {},
      wait_until: null,
      wait_message: null,
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'mock-task-2',
      client_id: 'mock-client-1',
      template_task_id: null,
      title: 'Upload Tax Documents',
      description: 'Upload your previous year tax returns and financial statements',
      task_type: 'document_upload',
      status: 'in_progress',
      order_index: 2,
      required: true,
      due_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      estimated_duration: 60,
      instructions: 'Please upload PDF copies of your tax returns from the last 2 years',
      metadata: {},
      wait_until: null,
      wait_message: null,
      created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'mock-task-3',
      client_id: 'mock-client-2',
      template_task_id: null,
      title: 'Schedule Initial Consultation',
      description: 'Book a 30-minute consultation call to discuss project requirements',
      task_type: 'meeting_scheduling',
      status: 'completed',
      order_index: 1,
      required: true,
      due_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      estimated_duration: 30,
      instructions: 'Use the calendar link provided to schedule your consultation',
      metadata: {},
      wait_until: null,
      wait_message: null,
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],

  templates: () => [
    {
      id: 'mock-template-1',
      agency_id: 'a1b2c3d4-e5f6-7890-1234-567890abcdef',
      name: 'Standard Onboarding',
      description: 'Complete onboarding process for new clients',
      tasks: [
        {
          id: 'template-task-1',
          title: 'Welcome Call',
          description: 'Initial welcome and orientation call',
          task_type: 'meeting_scheduling',
          order_index: 1,
          required: true,
          estimated_duration: 30,
          instructions: 'Schedule and complete welcome call with client',
          metadata: {}
        },
        {
          id: 'template-task-2',
          title: 'Document Collection',
          description: 'Collect all necessary client documents',
          task_type: 'document_upload',
          order_index: 2,
          required: true,
          estimated_duration: 60,
          instructions: 'Request and collect all required documentation',
          metadata: {}
        }
      ],
      is_active: true,
      created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'mock-template-2',
      agency_id: 'a1b2c3d4-e5f6-7890-1234-567890abcdef',
      name: 'Quick Setup',
      description: 'Streamlined setup for simple projects',
      tasks: [
        {
          id: 'template-task-3',
          title: 'Project Brief',
          description: 'Complete project requirements form',
          task_type: 'form_completion',
          order_index: 1,
          required: true,
          estimated_duration: 45,
          instructions: 'Fill out the detailed project brief form',
          metadata: {}
        }
      ],
      is_active: true,
      created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
};